apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-website-deployment
  labels:
    app: php-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-website
  template:
    metadata:
      labels:
        app: php-website
    spec:
      containers:
      - name: php-website
        image: sanjana0910/php_new3:v1
        ports:
        - containerPort: 80
